// Generated by gencpp from file test_ser_cli/robot_serviceResponse.msg
// DO NOT EDIT!


#ifndef TEST_SER_CLI_MESSAGE_ROBOT_SERVICERESPONSE_H
#define TEST_SER_CLI_MESSAGE_ROBOT_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <test_create_msg_new/robot_detail.h>

namespace test_ser_cli
{
template <class ContainerAllocator>
struct robot_serviceResponse_
{
  typedef robot_serviceResponse_<ContainerAllocator> Type;

  robot_serviceResponse_()
    : response()  {
    }
  robot_serviceResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef  ::test_create_msg_new::robot_detail_<ContainerAllocator>  _response_type;
  _response_type response;




  typedef boost::shared_ptr< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robot_serviceResponse_

typedef ::test_ser_cli::robot_serviceResponse_<std::allocator<void> > robot_serviceResponse;

typedef boost::shared_ptr< ::test_ser_cli::robot_serviceResponse > robot_serviceResponsePtr;
typedef boost::shared_ptr< ::test_ser_cli::robot_serviceResponse const> robot_serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_ser_cli

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'test_create_msg_new': ['/home/ton/catkin_ws/src/src_code/test_create_msg_new/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2369367726d718615d2024a5db3fae29";
  }

  static const char* value(const ::test_ser_cli::robot_serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2369367726d71861ULL;
  static const uint64_t static_value2 = 0x5d2024a5db3fae29ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_ser_cli/robot_serviceResponse";
  }

  static const char* value(const ::test_ser_cli::robot_serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_create_msg_new/robot_detail response\n\
\n\
\n\
================================================================================\n\
MSG: test_create_msg_new/robot_detail\n\
string name\n\
int16 year\n\
int16 weight\n\
";
  }

  static const char* value(const ::test_ser_cli::robot_serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_ser_cli::robot_serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_ser_cli::robot_serviceResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    s << std::endl;
    Printer< ::test_create_msg_new::robot_detail_<ContainerAllocator> >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_SER_CLI_MESSAGE_ROBOT_SERVICERESPONSE_H
