// Generated by gencpp from file test_ser_cli/robot_serviceRequest.msg
// DO NOT EDIT!


#ifndef TEST_SER_CLI_MESSAGE_ROBOT_SERVICEREQUEST_H
#define TEST_SER_CLI_MESSAGE_ROBOT_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_ser_cli
{
template <class ContainerAllocator>
struct robot_serviceRequest_
{
  typedef robot_serviceRequest_<ContainerAllocator> Type;

  robot_serviceRequest_()
    : name()  {
    }
  robot_serviceRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;




  typedef boost::shared_ptr< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_serviceRequest_

typedef ::test_ser_cli::robot_serviceRequest_<std::allocator<void> > robot_serviceRequest;

typedef boost::shared_ptr< ::test_ser_cli::robot_serviceRequest > robot_serviceRequestPtr;
typedef boost::shared_ptr< ::test_ser_cli::robot_serviceRequest const> robot_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_ser_cli

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'test_create_msg_new': ['/home/ton/catkin_ws/src/src_code/test_create_msg_new/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::test_ser_cli::robot_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_ser_cli/robot_serviceRequest";
  }

  static const char* value(const ::test_ser_cli::robot_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
";
  }

  static const char* value(const ::test_ser_cli::robot_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_ser_cli::robot_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_ser_cli::robot_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_SER_CLI_MESSAGE_ROBOT_SERVICEREQUEST_H
