// Generated by gencpp from file test_ser_cli/robot_service.msg
// DO NOT EDIT!


#ifndef TEST_SER_CLI_MESSAGE_ROBOT_SERVICE_H
#define TEST_SER_CLI_MESSAGE_ROBOT_SERVICE_H

#include <ros/service_traits.h>


#include <test_ser_cli/robot_serviceRequest.h>
#include <test_ser_cli/robot_serviceResponse.h>


namespace test_ser_cli
{

struct robot_service
{

typedef robot_serviceRequest Request;
typedef robot_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_service
} // namespace test_ser_cli


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_ser_cli::robot_service > {
  static const char* value()
  {
    return "8800708100fda626f86c83189e112add";
  }

  static const char* value(const ::test_ser_cli::robot_service&) { return value(); }
};

template<>
struct DataType< ::test_ser_cli::robot_service > {
  static const char* value()
  {
    return "test_ser_cli/robot_service";
  }

  static const char* value(const ::test_ser_cli::robot_service&) { return value(); }
};


// service_traits::MD5Sum< ::test_ser_cli::robot_serviceRequest> should match 
// service_traits::MD5Sum< ::test_ser_cli::robot_service > 
template<>
struct MD5Sum< ::test_ser_cli::robot_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_ser_cli::robot_service >::value();
  }
  static const char* value(const ::test_ser_cli::robot_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_ser_cli::robot_serviceRequest> should match 
// service_traits::DataType< ::test_ser_cli::robot_service > 
template<>
struct DataType< ::test_ser_cli::robot_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::test_ser_cli::robot_service >::value();
  }
  static const char* value(const ::test_ser_cli::robot_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_ser_cli::robot_serviceResponse> should match 
// service_traits::MD5Sum< ::test_ser_cli::robot_service > 
template<>
struct MD5Sum< ::test_ser_cli::robot_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_ser_cli::robot_service >::value();
  }
  static const char* value(const ::test_ser_cli::robot_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_ser_cli::robot_serviceResponse> should match 
// service_traits::DataType< ::test_ser_cli::robot_service > 
template<>
struct DataType< ::test_ser_cli::robot_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::test_ser_cli::robot_service >::value();
  }
  static const char* value(const ::test_ser_cli::robot_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_SER_CLI_MESSAGE_ROBOT_SERVICE_H
