// Generated by gencpp from file test_service_client/service_test.msg
// DO NOT EDIT!


#ifndef TEST_SERVICE_CLIENT_MESSAGE_SERVICE_TEST_H
#define TEST_SERVICE_CLIENT_MESSAGE_SERVICE_TEST_H

#include <ros/service_traits.h>


#include <test_service_client/service_testRequest.h>
#include <test_service_client/service_testResponse.h>


namespace test_service_client
{

struct service_test
{

typedef service_testRequest Request;
typedef service_testResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct service_test
} // namespace test_service_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_service_client::service_test > {
  static const char* value()
  {
    return "834f928ec74381cd9b270dead49151fa";
  }

  static const char* value(const ::test_service_client::service_test&) { return value(); }
};

template<>
struct DataType< ::test_service_client::service_test > {
  static const char* value()
  {
    return "test_service_client/service_test";
  }

  static const char* value(const ::test_service_client::service_test&) { return value(); }
};


// service_traits::MD5Sum< ::test_service_client::service_testRequest> should match 
// service_traits::MD5Sum< ::test_service_client::service_test > 
template<>
struct MD5Sum< ::test_service_client::service_testRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_service_client::service_test >::value();
  }
  static const char* value(const ::test_service_client::service_testRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_service_client::service_testRequest> should match 
// service_traits::DataType< ::test_service_client::service_test > 
template<>
struct DataType< ::test_service_client::service_testRequest>
{
  static const char* value()
  {
    return DataType< ::test_service_client::service_test >::value();
  }
  static const char* value(const ::test_service_client::service_testRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_service_client::service_testResponse> should match 
// service_traits::MD5Sum< ::test_service_client::service_test > 
template<>
struct MD5Sum< ::test_service_client::service_testResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_service_client::service_test >::value();
  }
  static const char* value(const ::test_service_client::service_testResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_service_client::service_testResponse> should match 
// service_traits::DataType< ::test_service_client::service_test > 
template<>
struct DataType< ::test_service_client::service_testResponse>
{
  static const char* value()
  {
    return DataType< ::test_service_client::service_test >::value();
  }
  static const char* value(const ::test_service_client::service_testResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_SERVICE_CLIENT_MESSAGE_SERVICE_TEST_H
