// Generated by gencpp from file test_service_client/service_testRequest.msg
// DO NOT EDIT!


#ifndef TEST_SERVICE_CLIENT_MESSAGE_SERVICE_TESTREQUEST_H
#define TEST_SERVICE_CLIENT_MESSAGE_SERVICE_TESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace test_service_client
{
template <class ContainerAllocator>
struct service_testRequest_
{
  typedef service_testRequest_<ContainerAllocator> Type;

  service_testRequest_()
    : requestNO(0)
    , request()
    , data()  {
    }
  service_testRequest_(const ContainerAllocator& _alloc)
    : requestNO(0)
    , request(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _requestNO_type;
  _requestNO_type requestNO;

   typedef  ::std_msgs::String_<ContainerAllocator>  _request_type;
  _request_type request;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::test_service_client::service_testRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_service_client::service_testRequest_<ContainerAllocator> const> ConstPtr;

}; // struct service_testRequest_

typedef ::test_service_client::service_testRequest_<std::allocator<void> > service_testRequest;

typedef boost::shared_ptr< ::test_service_client::service_testRequest > service_testRequestPtr;
typedef boost::shared_ptr< ::test_service_client::service_testRequest const> service_testRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_service_client::service_testRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_service_client::service_testRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_service_client

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_service_client::service_testRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_service_client::service_testRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_service_client::service_testRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_service_client::service_testRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_service_client::service_testRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_service_client::service_testRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_service_client::service_testRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "387f88e6d0e323049141ac3c7e9cf38e";
  }

  static const char* value(const ::test_service_client::service_testRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x387f88e6d0e32304ULL;
  static const uint64_t static_value2 = 0x9141ac3c7e9cf38eULL;
};

template<class ContainerAllocator>
struct DataType< ::test_service_client::service_testRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_service_client/service_testRequest";
  }

  static const char* value(const ::test_service_client::service_testRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_service_client::service_testRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 requestNO\n\
std_msgs/String request\n\
string data\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::test_service_client::service_testRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_service_client::service_testRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.requestNO);
      stream.next(m.request);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct service_testRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_service_client::service_testRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_service_client::service_testRequest_<ContainerAllocator>& v)
  {
    s << indent << "requestNO: ";
    Printer<int16_t>::stream(s, indent + "  ", v.requestNO);
    s << indent << "request: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.request);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_SERVICE_CLIENT_MESSAGE_SERVICE_TESTREQUEST_H
