// Generated by gencpp from file test_create_msg/robot_detail.msg
// DO NOT EDIT!


#ifndef TEST_CREATE_MSG_MESSAGE_ROBOT_DETAIL_H
#define TEST_CREATE_MSG_MESSAGE_ROBOT_DETAIL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_create_msg
{
template <class ContainerAllocator>
struct robot_detail_
{
  typedef robot_detail_<ContainerAllocator> Type;

  robot_detail_()
    : name()
    , weight(0.0)
    , noOfThruster(0)  {
    }
  robot_detail_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , weight(0.0)
    , noOfThruster(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef float _weight_type;
  _weight_type weight;

   typedef int16_t _noOfThruster_type;
  _noOfThruster_type noOfThruster;




  typedef boost::shared_ptr< ::test_create_msg::robot_detail_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_create_msg::robot_detail_<ContainerAllocator> const> ConstPtr;

}; // struct robot_detail_

typedef ::test_create_msg::robot_detail_<std::allocator<void> > robot_detail;

typedef boost::shared_ptr< ::test_create_msg::robot_detail > robot_detailPtr;
typedef boost::shared_ptr< ::test_create_msg::robot_detail const> robot_detailConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_create_msg::robot_detail_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_create_msg::robot_detail_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_create_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'test_create_msg': ['/home/ton/catkin_ws/src/src_code/test_create_msg/msg', '/home/ton/catkin_ws/src/src_code/test_create_msg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_create_msg::robot_detail_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_create_msg::robot_detail_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_create_msg::robot_detail_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_create_msg::robot_detail_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_create_msg::robot_detail_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_create_msg::robot_detail_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_create_msg::robot_detail_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48a1dd1c3cf1dd17dd60dbee884de278";
  }

  static const char* value(const ::test_create_msg::robot_detail_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48a1dd1c3cf1dd17ULL;
  static const uint64_t static_value2 = 0xdd60dbee884de278ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_create_msg::robot_detail_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_create_msg/robot_detail";
  }

  static const char* value(const ::test_create_msg::robot_detail_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_create_msg::robot_detail_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
float32 weight\n\
int16 noOfThruster\n\
";
  }

  static const char* value(const ::test_create_msg::robot_detail_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_create_msg::robot_detail_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.weight);
      stream.next(m.noOfThruster);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_detail_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_create_msg::robot_detail_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_create_msg::robot_detail_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "weight: ";
    Printer<float>::stream(s, indent + "  ", v.weight);
    s << indent << "noOfThruster: ";
    Printer<int16_t>::stream(s, indent + "  ", v.noOfThruster);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_CREATE_MSG_MESSAGE_ROBOT_DETAIL_H
