// Generated by gencpp from file s_c_plusminus/output.msg
// DO NOT EDIT!


#ifndef S_C_PLUSMINUS_MESSAGE_OUTPUT_H
#define S_C_PLUSMINUS_MESSAGE_OUTPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace s_c_plusminus
{
template <class ContainerAllocator>
struct output_
{
  typedef output_<ContainerAllocator> Type;

  output_()
    : equation()
    , result(0)  {
    }
  output_(const ContainerAllocator& _alloc)
    : equation(_alloc)
    , result(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _equation_type;
  _equation_type equation;

   typedef int16_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::s_c_plusminus::output_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::s_c_plusminus::output_<ContainerAllocator> const> ConstPtr;

}; // struct output_

typedef ::s_c_plusminus::output_<std::allocator<void> > output;

typedef boost::shared_ptr< ::s_c_plusminus::output > outputPtr;
typedef boost::shared_ptr< ::s_c_plusminus::output const> outputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::s_c_plusminus::output_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::s_c_plusminus::output_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace s_c_plusminus

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'s_c_plusminus': ['/home/ton/catkin_ws/src/src_code/s_c_plusminus/msg', '/home/ton/catkin_ws/src/src_code/s_c_plusminus/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::s_c_plusminus::output_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::s_c_plusminus::output_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::s_c_plusminus::output_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::s_c_plusminus::output_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::s_c_plusminus::output_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::s_c_plusminus::output_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::s_c_plusminus::output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bab23f51d169221c4e582476e5ea309";
  }

  static const char* value(const ::s_c_plusminus::output_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bab23f51d169221ULL;
  static const uint64_t static_value2 = 0xc4e582476e5ea309ULL;
};

template<class ContainerAllocator>
struct DataType< ::s_c_plusminus::output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "s_c_plusminus/output";
  }

  static const char* value(const ::s_c_plusminus::output_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::s_c_plusminus::output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string equation\n\
int16 result\n\
";
  }

  static const char* value(const ::s_c_plusminus::output_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::s_c_plusminus::output_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.equation);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct output_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::s_c_plusminus::output_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::s_c_plusminus::output_<ContainerAllocator>& v)
  {
    s << indent << "equation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.equation);
    s << indent << "result: ";
    Printer<int16_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // S_C_PLUSMINUS_MESSAGE_OUTPUT_H
