// Generated by gencpp from file s_c_plusminus/plusminus_servResponse.msg
// DO NOT EDIT!


#ifndef S_C_PLUSMINUS_MESSAGE_PLUSMINUS_SERVRESPONSE_H
#define S_C_PLUSMINUS_MESSAGE_PLUSMINUS_SERVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <s_c_plusminus/output.h>

namespace s_c_plusminus
{
template <class ContainerAllocator>
struct plusminus_servResponse_
{
  typedef plusminus_servResponse_<ContainerAllocator> Type;

  plusminus_servResponse_()
    : response()  {
    }
  plusminus_servResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef  ::s_c_plusminus::output_<ContainerAllocator>  _response_type;
  _response_type response;




  typedef boost::shared_ptr< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> const> ConstPtr;

}; // struct plusminus_servResponse_

typedef ::s_c_plusminus::plusminus_servResponse_<std::allocator<void> > plusminus_servResponse;

typedef boost::shared_ptr< ::s_c_plusminus::plusminus_servResponse > plusminus_servResponsePtr;
typedef boost::shared_ptr< ::s_c_plusminus::plusminus_servResponse const> plusminus_servResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace s_c_plusminus

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'s_c_plusminus': ['/home/ton/catkin_ws/src/src_code/s_c_plusminus/msg', '/home/ton/catkin_ws/src/src_code/s_c_plusminus/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9e80d5e6563aabd179f85f26537c29a";
  }

  static const char* value(const ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9e80d5e6563aabdULL;
  static const uint64_t static_value2 = 0x179f85f26537c29aULL;
};

template<class ContainerAllocator>
struct DataType< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "s_c_plusminus/plusminus_servResponse";
  }

  static const char* value(const ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "s_c_plusminus/output response\n\
\n\
\n\
================================================================================\n\
MSG: s_c_plusminus/output\n\
string equation\n\
int16 result\n\
";
  }

  static const char* value(const ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct plusminus_servResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::s_c_plusminus::plusminus_servResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    s << std::endl;
    Printer< ::s_c_plusminus::output_<ContainerAllocator> >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // S_C_PLUSMINUS_MESSAGE_PLUSMINUS_SERVRESPONSE_H
