// Generated by gencpp from file s_c_plusminus/plusminus_serv.msg
// DO NOT EDIT!


#ifndef S_C_PLUSMINUS_MESSAGE_PLUSMINUS_SERV_H
#define S_C_PLUSMINUS_MESSAGE_PLUSMINUS_SERV_H

#include <ros/service_traits.h>


#include <s_c_plusminus/plusminus_servRequest.h>
#include <s_c_plusminus/plusminus_servResponse.h>


namespace s_c_plusminus
{

struct plusminus_serv
{

typedef plusminus_servRequest Request;
typedef plusminus_servResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct plusminus_serv
} // namespace s_c_plusminus


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::s_c_plusminus::plusminus_serv > {
  static const char* value()
  {
    return "30760a2ae78bf5e8cc7c7a4386966418";
  }

  static const char* value(const ::s_c_plusminus::plusminus_serv&) { return value(); }
};

template<>
struct DataType< ::s_c_plusminus::plusminus_serv > {
  static const char* value()
  {
    return "s_c_plusminus/plusminus_serv";
  }

  static const char* value(const ::s_c_plusminus::plusminus_serv&) { return value(); }
};


// service_traits::MD5Sum< ::s_c_plusminus::plusminus_servRequest> should match 
// service_traits::MD5Sum< ::s_c_plusminus::plusminus_serv > 
template<>
struct MD5Sum< ::s_c_plusminus::plusminus_servRequest>
{
  static const char* value()
  {
    return MD5Sum< ::s_c_plusminus::plusminus_serv >::value();
  }
  static const char* value(const ::s_c_plusminus::plusminus_servRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::s_c_plusminus::plusminus_servRequest> should match 
// service_traits::DataType< ::s_c_plusminus::plusminus_serv > 
template<>
struct DataType< ::s_c_plusminus::plusminus_servRequest>
{
  static const char* value()
  {
    return DataType< ::s_c_plusminus::plusminus_serv >::value();
  }
  static const char* value(const ::s_c_plusminus::plusminus_servRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::s_c_plusminus::plusminus_servResponse> should match 
// service_traits::MD5Sum< ::s_c_plusminus::plusminus_serv > 
template<>
struct MD5Sum< ::s_c_plusminus::plusminus_servResponse>
{
  static const char* value()
  {
    return MD5Sum< ::s_c_plusminus::plusminus_serv >::value();
  }
  static const char* value(const ::s_c_plusminus::plusminus_servResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::s_c_plusminus::plusminus_servResponse> should match 
// service_traits::DataType< ::s_c_plusminus::plusminus_serv > 
template<>
struct DataType< ::s_c_plusminus::plusminus_servResponse>
{
  static const char* value()
  {
    return DataType< ::s_c_plusminus::plusminus_serv >::value();
  }
  static const char* value(const ::s_c_plusminus::plusminus_servResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // S_C_PLUSMINUS_MESSAGE_PLUSMINUS_SERV_H
