// Generated by gencpp from file s_c_plusminus/plusminus_servRequest.msg
// DO NOT EDIT!


#ifndef S_C_PLUSMINUS_MESSAGE_PLUSMINUS_SERVREQUEST_H
#define S_C_PLUSMINUS_MESSAGE_PLUSMINUS_SERVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace s_c_plusminus
{
template <class ContainerAllocator>
struct plusminus_servRequest_
{
  typedef plusminus_servRequest_<ContainerAllocator> Type;

  plusminus_servRequest_()
    : command()
    , inp1(0)
    , inp2(0)  {
    }
  plusminus_servRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , inp1(0)
    , inp2(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef int16_t _inp1_type;
  _inp1_type inp1;

   typedef int16_t _inp2_type;
  _inp2_type inp2;




  typedef boost::shared_ptr< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> const> ConstPtr;

}; // struct plusminus_servRequest_

typedef ::s_c_plusminus::plusminus_servRequest_<std::allocator<void> > plusminus_servRequest;

typedef boost::shared_ptr< ::s_c_plusminus::plusminus_servRequest > plusminus_servRequestPtr;
typedef boost::shared_ptr< ::s_c_plusminus::plusminus_servRequest const> plusminus_servRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace s_c_plusminus

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'s_c_plusminus': ['/home/ton/catkin_ws/src/src_code/s_c_plusminus/msg', '/home/ton/catkin_ws/src/src_code/s_c_plusminus/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "347a1b1972ef0811be4ba9fb2c72ee0e";
  }

  static const char* value(const ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x347a1b1972ef0811ULL;
  static const uint64_t static_value2 = 0xbe4ba9fb2c72ee0eULL;
};

template<class ContainerAllocator>
struct DataType< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "s_c_plusminus/plusminus_servRequest";
  }

  static const char* value(const ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n\
int16 inp1\n\
int16 inp2\n\
";
  }

  static const char* value(const ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.inp1);
      stream.next(m.inp2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct plusminus_servRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::s_c_plusminus::plusminus_servRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "inp1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.inp1);
    s << indent << "inp2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.inp2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // S_C_PLUSMINUS_MESSAGE_PLUSMINUS_SERVREQUEST_H
