// Generated by gencpp from file plus_minus_servic/kamtoobResponse.msg
// DO NOT EDIT!


#ifndef PLUS_MINUS_SERVIC_MESSAGE_KAMTOOBRESPONSE_H
#define PLUS_MINUS_SERVIC_MESSAGE_KAMTOOBRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <plus_minus_msg/what_input.h>

namespace plus_minus_servic
{
template <class ContainerAllocator>
struct kamtoobResponse_
{
  typedef kamtoobResponse_<ContainerAllocator> Type;

  kamtoobResponse_()
    : response()  {
    }
  kamtoobResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef  ::plus_minus_msg::what_input_<ContainerAllocator>  _response_type;
  _response_type response;




  typedef boost::shared_ptr< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> const> ConstPtr;

}; // struct kamtoobResponse_

typedef ::plus_minus_servic::kamtoobResponse_<std::allocator<void> > kamtoobResponse;

typedef boost::shared_ptr< ::plus_minus_servic::kamtoobResponse > kamtoobResponsePtr;
typedef boost::shared_ptr< ::plus_minus_servic::kamtoobResponse const> kamtoobResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace plus_minus_servic

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'plus_minus_msg': ['/home/ton/catkin_ws/src/src_code/plus_minus_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2870aa204943fa08ca8877035f95e07";
  }

  static const char* value(const ::plus_minus_servic::kamtoobResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2870aa204943fa0ULL;
  static const uint64_t static_value2 = 0x8ca8877035f95e07ULL;
};

template<class ContainerAllocator>
struct DataType< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plus_minus_servic/kamtoobResponse";
  }

  static const char* value(const ::plus_minus_servic::kamtoobResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plus_minus_msg/what_input response\n\
\n\
\n\
================================================================================\n\
MSG: plus_minus_msg/what_input\n\
string comand\n\
int16 inp1\n\
int16 inp2\n\
int16 result\n\
";
  }

  static const char* value(const ::plus_minus_servic::kamtoobResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kamtoobResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plus_minus_servic::kamtoobResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plus_minus_servic::kamtoobResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    s << std::endl;
    Printer< ::plus_minus_msg::what_input_<ContainerAllocator> >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLUS_MINUS_SERVIC_MESSAGE_KAMTOOBRESPONSE_H
