// Generated by gencpp from file plus_minus_servic/kamtoob.msg
// DO NOT EDIT!


#ifndef PLUS_MINUS_SERVIC_MESSAGE_KAMTOOB_H
#define PLUS_MINUS_SERVIC_MESSAGE_KAMTOOB_H

#include <ros/service_traits.h>


#include <plus_minus_servic/kamtoobRequest.h>
#include <plus_minus_servic/kamtoobResponse.h>


namespace plus_minus_servic
{

struct kamtoob
{

typedef kamtoobRequest Request;
typedef kamtoobResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct kamtoob
} // namespace plus_minus_servic


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plus_minus_servic::kamtoob > {
  static const char* value()
  {
    return "b82aa0d59edba103ba71ad6a815f7270";
  }

  static const char* value(const ::plus_minus_servic::kamtoob&) { return value(); }
};

template<>
struct DataType< ::plus_minus_servic::kamtoob > {
  static const char* value()
  {
    return "plus_minus_servic/kamtoob";
  }

  static const char* value(const ::plus_minus_servic::kamtoob&) { return value(); }
};


// service_traits::MD5Sum< ::plus_minus_servic::kamtoobRequest> should match 
// service_traits::MD5Sum< ::plus_minus_servic::kamtoob > 
template<>
struct MD5Sum< ::plus_minus_servic::kamtoobRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plus_minus_servic::kamtoob >::value();
  }
  static const char* value(const ::plus_minus_servic::kamtoobRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plus_minus_servic::kamtoobRequest> should match 
// service_traits::DataType< ::plus_minus_servic::kamtoob > 
template<>
struct DataType< ::plus_minus_servic::kamtoobRequest>
{
  static const char* value()
  {
    return DataType< ::plus_minus_servic::kamtoob >::value();
  }
  static const char* value(const ::plus_minus_servic::kamtoobRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plus_minus_servic::kamtoobResponse> should match 
// service_traits::MD5Sum< ::plus_minus_servic::kamtoob > 
template<>
struct MD5Sum< ::plus_minus_servic::kamtoobResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plus_minus_servic::kamtoob >::value();
  }
  static const char* value(const ::plus_minus_servic::kamtoobResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plus_minus_servic::kamtoobResponse> should match 
// service_traits::DataType< ::plus_minus_servic::kamtoob > 
template<>
struct DataType< ::plus_minus_servic::kamtoobResponse>
{
  static const char* value()
  {
    return DataType< ::plus_minus_servic::kamtoob >::value();
  }
  static const char* value(const ::plus_minus_servic::kamtoobResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUS_MINUS_SERVIC_MESSAGE_KAMTOOB_H
