// Generated by gencpp from file plus_minus_ser_cli/plus_ser.msg
// DO NOT EDIT!


#ifndef PLUS_MINUS_SER_CLI_MESSAGE_PLUS_SER_H
#define PLUS_MINUS_SER_CLI_MESSAGE_PLUS_SER_H

#include <ros/service_traits.h>


#include <plus_minus_ser_cli/plus_serRequest.h>
#include <plus_minus_ser_cli/plus_serResponse.h>


namespace plus_minus_ser_cli
{

struct plus_ser
{

typedef plus_serRequest Request;
typedef plus_serResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct plus_ser
} // namespace plus_minus_ser_cli


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plus_minus_ser_cli::plus_ser > {
  static const char* value()
  {
    return "924fbc742266a2d82feb8ba54d391a66";
  }

  static const char* value(const ::plus_minus_ser_cli::plus_ser&) { return value(); }
};

template<>
struct DataType< ::plus_minus_ser_cli::plus_ser > {
  static const char* value()
  {
    return "plus_minus_ser_cli/plus_ser";
  }

  static const char* value(const ::plus_minus_ser_cli::plus_ser&) { return value(); }
};


// service_traits::MD5Sum< ::plus_minus_ser_cli::plus_serRequest> should match 
// service_traits::MD5Sum< ::plus_minus_ser_cli::plus_ser > 
template<>
struct MD5Sum< ::plus_minus_ser_cli::plus_serRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plus_minus_ser_cli::plus_ser >::value();
  }
  static const char* value(const ::plus_minus_ser_cli::plus_serRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plus_minus_ser_cli::plus_serRequest> should match 
// service_traits::DataType< ::plus_minus_ser_cli::plus_ser > 
template<>
struct DataType< ::plus_minus_ser_cli::plus_serRequest>
{
  static const char* value()
  {
    return DataType< ::plus_minus_ser_cli::plus_ser >::value();
  }
  static const char* value(const ::plus_minus_ser_cli::plus_serRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plus_minus_ser_cli::plus_serResponse> should match 
// service_traits::MD5Sum< ::plus_minus_ser_cli::plus_ser > 
template<>
struct MD5Sum< ::plus_minus_ser_cli::plus_serResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plus_minus_ser_cli::plus_ser >::value();
  }
  static const char* value(const ::plus_minus_ser_cli::plus_serResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plus_minus_ser_cli::plus_serResponse> should match 
// service_traits::DataType< ::plus_minus_ser_cli::plus_ser > 
template<>
struct DataType< ::plus_minus_ser_cli::plus_serResponse>
{
  static const char* value()
  {
    return DataType< ::plus_minus_ser_cli::plus_ser >::value();
  }
  static const char* value(const ::plus_minus_ser_cli::plus_serResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUS_MINUS_SER_CLI_MESSAGE_PLUS_SER_H
